name: CI

on:
  push: # 一度動作確認してActionsが動きそうならオフにする # オフにしないとpushの無限ループにおちいるよ。

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        git config user.name ${{NAME}}
        git config user.email ${{EMAIL}}
        git remote set-url origin https://${{NAME}}:${{ secrets.GITHUB_PASS }}@github.com/${{NAME}}/${{REPO}}
        git branch
        git checkout master
        git branch
        ./omikuji.sh >> README.md
        git add .
        git commit -m "update!"
        git push origin master
      env:
        NAME: ykhirao
        EMAIL: yuki.dees39th@gmail.com
        REPO: write-code-everyday-bot
