name: Node CI

# on:
#   schedule:
#   - cron: 0 6 * * *

on:
  schedule:
  - cron: 0 13 * * *

# on:
#   push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        git config user.name "ykhirao-bot"
        git config user.email "yuki.dees39th@gmail.com"
        git remote set-url origin https://ykhirao:${{ secrets.GITHUB_PASS }}@github.com/ykhirao/write-code-everyday-bot
        git branch
        git checkout master
        git branch
        ./omikuji.sh >> README.md
        git add .
        git commit -m "update!"
        git push origin master
      env:
        CI: true
        SSH_KEY: ${{ secrets.SSH_KEY }}
